### ISSUE TITLE
More information regarding usage in controllers/models

### ISSUE THREAD

**Issue by BunnyBacon** [pauldowman/better_logging#3]
Hello!

Commenting quickly, I used the plugin installation. Then tried to catch my exception:

log.error "oops", e

This gave me undefined method log error. Where am I supposed to define this, and how?

**Comment by pauldowman** [comment]
Thanks for catching this, there was a typo in the docs, fixed in 07ba41e.

It should be `logger.error` (or `Rails.logger.error` if you're in a class that doesn't have the method `logger` defined). That's the standard way to get the logger object in Rails (it just happens to be an enhanced version of the logger if you're using this plugin).
